language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux
  - osx
  
sudo:false

cache:
  directories:
    -'$HOME/.m2/repository'
  
before_script:
  - psql -c 'create database storedb;' -U postgres
