language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories: -'$HOME/.m2/repository'
script: mvn clean install site:deploy -Pwildfly-managed-arquillian
deploy:
  provider: openshift
  user: denis@devtty.de
  password:
    secure: MCL+EL0nrkfQN46KhKAOUsn+G0fIvwyRzlnJGUpWEROmvgL2QLilLG9N91hdJS+j59togHc8HpAvlCOIxfXKFwsDBLBQ1+9rDPh1iEvVchEixh/7kQG0aO/S6CXCZgl8DjmW8+JtWS/zXlLpBykoWKb5sKcp3D9HvtCXrSW43gA=
  app: store
  domain: devtty
  on:
    repo: devtty/store
    